# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x08mpes.llm\"\xb0\x01\n\nGenRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_p\x18\x04 \x01(\x02\x12\r\n\x05top_k\x18\x05 \x01(\x05\x12\x16\n\x0erepeat_penalty\x18\x06 \x01(\x02\x12\x18\n\x10presence_penalty\x18\x07 \x01(\x02\x12\x19\n\x11\x66requency_penalty\x18\x08 \x01(\x02\",\n\x08GenReply\x12\x11\n\tgenerated\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2B\n\nLLMService\x12\x34\n\x08Generate\x12\x14.mpes.llm.GenRequest\x1a\x12.mpes.llm.GenReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENREQUEST']._serialized_start=24
  _globals['_GENREQUEST']._serialized_end=200
  _globals['_GENREPLY']._serialized_start=202
  _globals['_GENREPLY']._serialized_end=246
  _globals['_LLMSERVICE']._serialized_start=248
  _globals['_LLMSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
