# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x08mpes.stt\"J\n\x11TranscribeRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\".\n\x0fTranscribeReply\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2R\n\nSTTService\x12\x44\n\nTranscribe\x12\x1b.mpes.stt.TranscribeRequest\x1a\x19.mpes.stt.TranscribeReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEREQUEST']._serialized_start=23
  _globals['_TRANSCRIBEREQUEST']._serialized_end=97
  _globals['_TRANSCRIBEREPLY']._serialized_start=99
  _globals['_TRANSCRIBEREPLY']._serialized_end=145
  _globals['_STTSERVICE']._serialized_start=147
  _globals['_STTSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
